config/routes.rb
IndvProjV1::Application.routes.draw do
  resources :reports do
    collection do
      get 'avgsearch'
      get 'period'
    end
  end

  resources :orders

  resources :products
  get '_period' => 'report#period'
  get '_products' => 'product#products'

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :products
  has_many :reports, through: :products


  validates :quantity, :numericality => { :only_integer => true }

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reports, through: :orders

  validates :price, :numericality => { :only_integer => true }
  validates :quantity, :numericality => { :greater_than_or_equal_to => 0}

  def name_with_quantity
    "#{name} Product | #{quantity} Product"
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  def products
    @products ||= find_products
  end

  def orders
    @orders ||= find_orders
    @orders ||= find_average
  end


  def find_products
    products = Product.order(:name)
    products = products.where("quantity <= ?",quantity)
  end

  def find_order
    order = Order.order(:sale_date)
    order = orders.where("order_date >= ?", start_date)
    order = orders.where("order_date <= ?", end_date)
  end

  def find_average
    orders = Order.order(:quantity)
    orders = orders.where("product_id == ?", "".average("quantity"))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show

  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:product_id, :quantity, :price, :total, :date)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  def avgsearch
    @report=Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:product_id, :order_id, :quantity, :name, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndvProjects</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Beauty Inventory</h1>
<%= link_to "Products", products_path %>
  <%= link_to "Order", orders_path %>
  <%= link_to "Reports", reports_path %>

<hr>
<%= yield %>
<hr>

Copyright 2014-2015 by Christie Nguyen. All Rights Reserved.
</body>

</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :name_with_quantity, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <label for="price"> Price </label><br>
    <%= f.text_field :price %>


  </div>
  <div class="field">
    <P>Total</P>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :order => [:month, :day, :year] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= javascript_include_tag "orders" %>

app/views/orders/_period.html.erb
<%if @report.start_date.blank? || @report.end_date.blank? || @report.start_date > @report.end_date%>
    <div id = "Notice"><h1>Go back and check the dates.</h1></div>
<%end%>
<br>
<h2>Date Search</h2>
<Br>
<% @report.orders.each do |b| %>
    <p><%="Product ID: #{b.product_id}"%>
      <%="Sale Date: #{b.sale_date}"%>
      <%="Product Qty: #{b.quantity}"%></p>
<%end%>


<%= link_to 'Back', reports_path %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<br>
<h2>Listing orders</h2>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_id %></td>
        <td><%= order.quantity %></td>
        <td><%=  number_to_currency(order.price, precision:2) %></td>
        <td><%= order.total %></td>
        <td><%= order.date.to_formatted_s(:long) %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<br>
<h2>New order</h2>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Total:</strong>
  <%= number_to_currency(@order.total) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_products.html.erb
<h2> Quantity Report</h2>
<Br>
<% @report.products.each do |b| %>
    <p><%="QTY: #{b.quantity}"%></p>
<%end%>

app/views/products/edit.html.erb
<h2>Editing product</h2>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<br>
<h2>Listing products</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<br>
<h2>New product</h2>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reports/_avgsearch.html.erb
<h2>Average Search</h2>
<Br>
Objective: showing the average number of each
item sold per week so that I can predict future sales.

<% @report.orders.each do |b| %>
    <p><%="date: #{b.date}"%>
<%end%>

<%= link_to 'Back', reports_path %>

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_period.html.erb
<br>
<h2>Period Reports between dates</h2>
<Br>
Objective: how many items were sold in a given time period
<br>
Review the total gross revenue for any time period
<% @report.orders.each do |b| %>
    <p><%="Product ID: #{b.name}"%>
      <%="QTY: #{b.quantity}"%></p>

    <%=number_to_currency(@reports.orders.sum(:price) * @reports.orders.sum(:product)) %>
<%end%>

<%= link_to 'Back', reports_path %>

app/views/reports/avgsearch.html.erb
<h2>Product Avg Search</h2>

<p>Please select a Product to show the average number of that item sold per week</p>
<BR>
Objective: showing the average number of each item sold per week so that I can predict future sales.

<%= form_for (@report) do |f|%>

    <div class="field">
      <%=f.label :product_id%><br />
      <%= f.collection_select :product_id, Product.all, :id, :name, :prompt => true %>
    </div>

    <div class="actions">
      <%=f.submit "Search"%>
    </div>
<%end%>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<Br>
<h2>Listing reports</h2>

<%= link_to "Quantity Search", new_report_path%>
<%= link_to "Date Search", period_reports_path%>
<%= link_to "Average Search", avgsearch_reports_path%>

<Br>
<Br>

app/views/reports/new.html.erb
<br>
<h2>Quantity Search</h2>
<Br>
<p>Objective: Find products that is less then or equal to the given number</p>
<br>
Determine which items have a stock
level below a given amount
<%= form_for (@report) do |f|%>

    <div class="field">
      <%=f.label :quantity%><br />
      <%= f.number_field :quantity %>
    </div>

    <div class="actions">
      <%=f.submit "Search"%>
    </div>
<%end%>


<%= link_to 'Back', reports_path %>

app/views/reports/period.html.erb
<Br><h2>Period Search</h2>
<Br>
Objective: To determine how many items were
sold in a given time period
<%= form_for Report.new do |f|%>

    <div class="field">
      <%=f.label :start_date%><br />
      <%=f.date_select :start_date, :order => [:month, :day, :year]%>
    </div>

    <div class = "field">
      <%f.label :end_date%><br />
      <%=f.date_select :end_date, :order => [:month, :day, :year]%>
    </div>

    <div class="actions">
      <%=f.submit "Search"%>
    </div>
<%end%>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<%if @report.quantity !=nil%>
    <%= render :partial => "products/products"%>

    <%if @report.product_id!=nil%>
        <%= render :partial => "reports/avgsearch"%>

    <%else%>
        <%= render :partial => "orders/period"%>
    <%end%>
<%end%>

<%= link_to 'Edit', edit_report_path(@reports) %> |
<%= link_to 'Back', reports_path %>